dataset:
  name: SemanticNuScenes
  dataset_path:  # path/to/your/dataset
  cache_dir: ./logs/cache
  class_weights: []
  test_result_folder: ./test
  use_cache: false
  sampler:
    name: 'SemSegRandomSampler'
model:
  name: RandLANet
  batcher: DefaultBatcher
  ckpt_path: # path/to/your/checkpoint
  num_neighbors: 16
  num_layers: 4
  num_points: 45056
  #num_classes: 15
  num_classes: 9
  ignored_label_inds: [0]
  sub_sampling_ratio: [4, 4, 4, 4]
  in_channels: 3
  dim_features: 8
  dim_output: [16, 64, 128, 256]
  grid_size: 0.06
  augment:
    recenter:
      dim: [0, 1]
pipeline:
  name: SemanticSegmentation
  optimizer:
    lr: 0.001
  scheduler:
    step_size: 10
    gamma: 0.1
  batch_size: 4
  main_log_dir: ./logs
  max_epoch: 35
  save_ckpt_freq: 5
  scheduler_gamma: 0.9886
  test_batch_size: 1
  train_sum_dir: train_log
  val_batch_size: 4
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
