dataset:
  name: mtNuScenes
  dataset_path: # path/to/your/dataset
  cache_dir: ./logs/cache
  test_result_folder: ./test
  #use_cache: true
  #steps_per_epoch_train: 1
  #steps_per_epoch_valid: 1

model:
  name: mtSalsaNext
  ckpt_path: # path/to/your/checkpoint

  batcher: "ignore"

  od_classes: [
    'pedestrian', 'bike', 'car', 'other_vehicle'
  ]
  od_num_classes: 4
  ss_classes: [
    'pedestrian', 'bike', 'car', 'other_vehicle', 'driveable_surface', 'sidewalk', 'terrain', 'manmade', 'vegetation'
  ]
  ss_num_classes: 9
  ignore_label_inds: [-1]
  num_per_class: [46687, 7834, 501416, 410507, 4069879, 746905, 696526, 2067585, 1565272]

  max_points: 150000 # max of any scan in dataset
  sensor_name: ""
  sensor_type: "spherical" # projective
  sensor_fov_up: 10
  sensor_fov_down: -30
  sensor_img_width: 2048
  sensor_img_height: 64
  sensor_img_means: #range,x,y,z,signal
      [10.,  0.,  0., -1., 0.2]
  sensor_img_stds: #range,x,y,z,signal
      [10., 10., 10.,  1., 0.2]

  loss:
    reg_smooth_l1:
      beta: 0.11
      loss_weight: -1.0
      log_weight: 0.0
    dir_cross_entropy:
      loss_weight: -1.0
      log_weight: 0.0
    cls_cross_entropy:
      loss_weight: -1.0
      log_weight: 0.0
    seg_cross_entropy:
      loss_weight: 0.0
      log_weight: 0.0

  head:
    sizes: [
      [0.66344886, 0.7256437, 1.75748069],    # pedestrian
      [0.60058911, 1.68452161, 1.27192197],   # bike
      [1.95017717, 4.60718145, 1.72270761],   # car
      [1.95017717, 4.60718145, 1.72270761]    # other_vehicle
    ]
    nms_pre: 10000
    score_thr: 0.1
    dir_offset: 0.7854
    rotations: [0, 1.57]
    iou_thr: [[0.3, 0.6]]

  augment:
    #PointShuffle: True
    #ObjectRangeFilter:
    #  point_cloud_range: [-50, -50, -5, 50, 50, 3.0]
    #ObjectSample:
    #  pickle_path: '/data/nuScenes/bboxes.pkl'
    #  min_points_dict:
    #    pedestrian: 10
    #    bike: 10
    #    car: 5
    #    other_vehicle: 5
    #  sample_dict:
    #    pedestrian: 10
    #    bike: 10
    #    car: 15
    #    other_vehicle: 15



pipeline:
  name: Multitask
  test_compute_metric: true
  batch_size: 4
  val_batch_size: 4
  test_batch_size: 4
  #num_workers: 1
  num_workers: 4
  save_ckpt_freq: 5
  max_epoch: 200
  main_log_dir: ./logs
  train_sum_dir: train_log
  grad_clip_norm: 2

  optimizer:
    lr: 0.001
    #lr: 0.0001
    betas: [0.95, 0.99]
    weight_decay: 0.01

  # evaluation properties
  overlaps: [0.7]
  similar_classes: {
    #motorcycle: bicycle
  }
  difficulties: [0]
  summary:
    record_for: []
    max_pts:
    use_reference: false
    max_outputs: 1
