name: Ubuntu CI

on:
  workflow_dispatch:
  push:
    branches: [master, dev]
  pull_request:
    types: [opened, reopened, synchronize]

env:
  NPROC: 2
  PIP_VER: "21.1.1"
  WHEEL_VER: "0.38.4"
  PYTEST_VER: "7.1.2"
  PYTEST_RANDOMLY_VER: "3.8.0"

jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install Open3D
        run: |
          echo Installing dependencies
          set +x
          pip install -U pip=="$PIP_VER" wheel="$WHEEL_VER" pytest=="$PYTEST_VER" \
                         pytest-randomly=="$PYTEST_RANDOMLY_VER"
          pip install -r requirements-tensorflow.txt -r requirements-torch.txt
          echo Installing requirements
          pip install open3d --trusted-host www.open3d.org -f http://www.open3d.org/docs/latest/getting_started.html

      - name: Run examples/tests
        run: |
          set +x
          source set_open3d_ml_root.sh
          echo Add --randomly-seed=SEED to the test command to reproduce test order.
          python -m pytest tests
